# 1. Numpy Basics

In [1]:
import numpy as np

my_list = [10, 20, 50, 60, 70]
my_list

[10, 20, 50, 60, 70]

In [2]:
x = np.array(my_list)
x

array([10, 20, 50, 60, 70])

In [3]:
type(x)

numpy.ndarray

In [4]:
matrix = np.array([[4,6,8,7], [20,5,6,9]])
matrix

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

In [5]:
from numpy import random
x = random.rand(15) # uniform distribution between 0 and 1

array([0.05695737, 0.46098558, 0.66545975, 0.03908441, 0.73079367,
       0.52509469, 0.71497311, 0.93607884, 0.54497664, 0.59198517,
       0.82733382, 0.07110816, 0.40204775, 0.20404138, 0.54088347])

In [6]:
y = random.rand(5, 5) # matrix
y

array([[0.76685874, 0.8949583 , 0.44222214, 0.73012391, 0.76475221],
       [0.50919586, 0.90857107, 0.28076996, 0.14323481, 0.30070822],
       [0.60186174, 0.16551796, 0.36049521, 0.94891115, 0.57884662],
       [0.04584665, 0.71863148, 0.31618209, 0.49958204, 0.68378299],
       [0.37759434, 0.80104955, 0.02948398, 0.23303155, 0.55818042]])

In [9]:
z = random.randint(50, 60, 100) # uniformly distributed rower, upper, # of elems
z

array([53, 58, 54, 50, 59, 53, 55, 52, 56, 52, 54, 52, 53, 54, 54, 51, 51,
       52, 56, 51, 53, 56, 55, 50, 51, 52, 56, 53, 52, 57, 57, 59, 55, 56,
       51, 59, 55, 50, 51, 54, 58, 50, 59, 55, 55, 51, 59, 55, 57, 54, 56,
       57, 52, 52, 59, 50, 50, 56, 51, 59, 59, 53, 59, 57, 54, 52, 53, 50,
       51, 58, 53, 54, 55, 58, 58, 56, 50, 59, 53, 59, 50, 50, 55, 50, 54,
       52, 51, 50, 54, 59, 58, 53, 53, 55, 58, 54, 52, 59, 57, 56])

In [12]:
x = np.random.randn(3, 2) # normal distribution
x

array([[-0.59087037,  0.67918267],
       [ 0.05687187,  2.20410719],
       [-0.90696364, -0.32270866]])

In [14]:
x = np.arange(1,50) # evenly spaced values
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [15]:
y = np.arange(1,50, 5) # start, end, step
y

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [17]:
eye = np.eye(5,5)
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
one = np.ones((5,5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [25]:
zeros2D = np.zeros((5,3))
zeros2D

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
x = int(input('Enter an positive integer: '))
y = np.random.randint(0, x, 20)
y

Enter an int: 7


array([5, 2, 3, 0, 2, 1, 4, 2, 5, 6, 4, 4, 2, 1, 5, 1, 5, 0, 6, 5])

# 3. Shape, Length, Type, Reshape, and Max/Min values

In [33]:
# rand, randn, randint, eye, ones, zeros
my_list = [-30, 4, 50, 60, 29, 15, 22,90]
x = np.array(my_list)
x

array([-30,   4,  50,  60,  29,  15,  22,  90])

In [34]:
len(x)

8

In [36]:
x.shape

(8,)

In [37]:
x.dtype

dtype('int64')

In [38]:
type(x)

numpy.ndarray

In [44]:
# len(), shape, dtype, type(), max(), min()
max(x)
min(x)

-30

In [45]:
z= x.reshape(2,4)
z

array([[-30,   4,  50,  60],
       [ 29,  15,  22,  90]])

In [47]:
#index = x.index(max(x))
z = x.argmax()
z
x[z]

90

In [48]:
y = x.argmin()
y
x[y]

-30

In [49]:
x = np.random.randint(300,500, (4,5))
x

array([[329, 310, 378, 359, 353],
       [480, 327, 445, 453, 401],
       [413, 435, 423, 300, 474],
       [484, 342, 377, 303, 454]])

In [63]:
x = np.random.randint(-1000, 1001, (20,20))
max(x.reshape(400,))
print(x.min())
print(x.max())
print(x.sum())

-999
997
7643


In [64]:
min(x.reshape(400,))

-999

In [65]:
sum(x.reshape(400,))

7643

In [56]:
x = np.arange(300,500, 10)
x

array([300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420,
       430, 440, 450, 460, 470, 480, 490])

In [57]:
x.shape

(20,)

In [60]:
y =x.reshape(4,5)
y

array([[300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440],
       [450, 460, 470, 480, 490]])

In [61]:
y.shape

(4, 5)

# 4. Mathematical Operations

In [69]:
x = np.arange(1, 10)
print(x)
y = np.arange(1, 10)
print(y)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [67]:
sum = x + y
print(sum)

[ 2  4  6  8 10 12 14 16 18]


In [68]:
squared = x*x
print(squared)

[ 1  4  9 16 25 36 49 64 81]


In [70]:
sqrt = np.sqrt(x)
print(sqrt)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [71]:
z = np.exp(y)
print(z)

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


In [74]:
x = [3, 20, 30]
y = [4, 6, 7]
x = np.array(x)
y = np.array(y)
z = (x-y)**2
print(z)
dist = np.sqrt(z).sum()
print(dist)


[  1 196 529]
38.0


# Slicing and Indexing

In [77]:
x = np.array([20, 40, 50, 21, 15])
print(x)

[20 40 50 21 15]


In [78]:
print(x[2])

50


In [79]:
print(x[0: -1])

[20 40 50 21]


In [80]:
# Broadcasting
x[0:2] = 10
print(x)

[10 10 50 21 15]


In [82]:
matrix = np.random.randint(1, 10, (5,5))
print(matrix)

[[6 1 3 5 5]
 [7 1 7 1 7]
 [4 7 4 6 3]
 [9 9 3 1 4]
 [4 9 1 4 4]]


In [86]:
# get a row
print(matrix[2]) # row
print(matrix[2, 3]) # row, column
print(matrix[2][3])

[4 7 4 6 3]
6
6


In [89]:
mini_matrix = matrix[:3] # row 0, 1, 2
print(mini_matrix)

[[6 1 3 5 5]
 [7 1 7 1 7]
 [4 7 4 6 3]]


In [91]:
mini_matrix =  matrix[:, 2:] # all rows, colums from 2
print(mini_matrix)

[[3 5 5]
 [7 1 7]
 [4 6 3]
 [3 1 4]
 [1 4 4]]


In [92]:
matrix.shape

(5, 5)

In [93]:
matrix[4] = -1
print(matrix)

[[ 6  1  3  5  5]
 [ 7  1  7  1  7]
 [ 4  7  4  6  3]
 [ 9  9  3  1  4]
 [-1 -1 -1 -1 -1]]


In [94]:
matrix[0][4] *= 2
print(matrix)

[[ 6  1  3  5 10]
 [ 7  1  7  1  7]
 [ 4  7  4  6  3]
 [ 9  9  3  1  4]
 [-1 -1 -1 -1 -1]]


In [95]:
matrix = np.random.randint(1, 10, (5,5))
print(matrix)

[[4 5 9 6 5]
 [1 1 7 7 7]
 [4 8 1 7 5]
 [1 6 2 1 9]
 [6 5 1 9 8]]


In [97]:
new_matrix = matrix[ matrix > 3] # become one-dim
new_matrix.shape
print(new_matrix)
type(new_matrix)

[4 5 9 6 5 7 7 7 4 8 7 5 6 9 6 5 9 8]


numpy.ndarray

In [98]:
new_matrix = matrix[ matrix%2==0] # [condition]
print(new_matrix)

[4 6 4 8 6 2 6 8]


In [99]:
new_matrix = matrix[matrix%2 == 1]
print(new_matrix)

[5 9 5 1 1 7 7 7 1 7 5 1 1 9 5 1 9]


In [100]:
# Conditonal replacement of elements with new values
matrix = np.random.randint(-5, 5, (5,5))
print(matrix)

[[-5  3 -5  2 -3]
 [-1  0 -5  4  0]
 [-1 -5 -4  2 -3]
 [-5 -2 -1 -5  2]
 [-2  1  2 -2 -3]]


In [101]:
matrix[matrix < 0] = 0
matrix

array([[0, 3, 0, 2, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 2],
       [0, 1, 2, 0, 0]])

In [103]:
matrix[matrix%2 == 1] = 25
matrix

array([[ 0, 25,  0,  2,  0],
       [ 0,  0,  0,  4,  0],
       [ 0,  0,  0,  2,  0],
       [ 0,  0,  0,  0,  2],
       [ 0, 25,  2,  0,  0]])