# Introduction
* loading
* sorting
* manipulating

In [1]:
import numpy
numpy.__version__

'1.19.2'

In [2]:
import numpy as np

In [3]:
# np.<TAB>
# np?

# 1. Data Types
* integer
* list

In [4]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
print(type(L))
print(type(L[0]))

<class 'list'>
<class 'int'>


In [7]:
L2 = [str(c) for c in L]
print(L2)
type(L2[0])

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


str

In [8]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3] # flexibility with cost

[bool, str, float, int]

In [12]:
# Fixed-Type Arrays in Python
import array
L = list(range(10))
A = array.array('i', L)
print(A)
print(type(A))
# python: list, array -- array.array
# numpy array -- numpy.ndarray

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
<class 'array.array'>


In [13]:
import numpy as np
A = np.array([1,4,2,3])
print(A)
print(type(A))

[1 4 2 3]
<class 'numpy.ndarray'>


In [15]:
arr = np.array([1,2,3,4], dtype='float32')
print(arr)
print(type(arr))
print(arr.dtype)

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
float32


### Creating Arrays from Scratch

In [16]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [19]:
np.arange(0, 20, 2) # start, stop, step

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
np.linspace(0, 1, 5) # start, stop(included), num of elems

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
np.random.random((3,3)) # uniformly distributed between 0 and 1

array([[0.91254725, 0.30214652, 0.11052374],
       [0.80127744, 0.68324637, 0.62096422],
       [0.9782346 , 0.6711035 , 0.37928409]])

In [26]:
np.random.normal(0,1, (3,3)) # mean, standard deviation

array([[-0.28134931, -2.02073986,  0.98168251],
       [-0.42417329, -0.49991448,  2.32221657],
       [ 0.11645461, -1.35817455, -0.35383675]])

In [28]:
np.random.randint(0, 10, (3,3))

array([[0, 8, 7],
       [8, 0, 7],
       [3, 0, 5]])

In [29]:
np.empty(3) 

array([0., 1., 1.])

### NumPy Standary Data Types

In [30]:
np.zeros(10, dtype='int16') # Python data type

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [32]:
np.zeros(10, dtype=np.int16) # NumPy data type

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

# 2. NumPy Arrays
* Attributes
* Indexing
* Slicing
* Reshaping
* Joining and splitting

### Numpy Array Attributes

In [33]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [36]:
print(f'ndim: {x3.ndim}, shape: {x3.shape}, size: {x3.size}')
print(f'itmesize: {x3.itemsize} bytes, nbytes (one item): {x3.nbytes} bytes (total)')

ndim: 3, shape: (3, 4, 5), size: 60
itmesize: 8 bytes, nbytes (one item): 480 bytes (total)


### Array Indexing: Accessing Single Elements

In [37]:
print(x1)
print(x1[0])

[5 0 3 3 7 9]
5


In [38]:
print(x1[-1])
print(x1[-2])

9
7


In [39]:
print(x2[0,0])
print(x2[2,0])

3
1


In [40]:
x2[0,0] = 12
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [42]:
# NumPy arrays have a fixed type
x1[0] = 3.141592 # truncated
print(x1)

[3 0 3 3 7 9]


### Array Slicing: Accessing Subarrays
* x[start:stop:step]

In [43]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [45]:
print(x[:5])
print(x[5:])
print(x[4:7])

[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]


In [46]:
print(x[::2])
print(x[1::2])

[0 2 4 6 8]
[1 3 5 7 9]


In [48]:
print(x[::-1]) # reversed
print(x[5::-2])

[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


In [51]:
print(x2[:2, :3])
print(x2[:3, ::2])

[[12  5  2]
 [ 7  6  8]]
[[12  2]
 [ 7  8]
 [ 1  7]]


In [52]:
print(x2[::-1, ::-1])

[[ 7  7  6  1]
 [ 8  8  6  7]
 [ 4  2  5 12]]


In [53]:
print(x2[:, 0]) # first column
print(x2[0, :]) # first row
print(x2[0]) # frist row

[12  7  1]
[12  5  2  4]
[12  5  2  4]


In [54]:
x2_sub = x2[:2, :2]
x2_sub[0,0] = 30
print(x2_sub) # subarrays as no-copy views
print(x2)

[[30  5]
 [ 7  6]]
[[30  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [55]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy[0,0] = 111
print(x2_sub_copy)
print(x2)

[[111   5]
 [  7   6]]
[[30  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Reshaping of Arrays

In [56]:
grid = np.arange(1, 10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
x = np.array([1,2,3]) 
print(x.shape) # (3,) not (3, 1)
y = x.reshape((1,3))
print(y.shape) # (1,3) not (, 3)
x_row = x[np.newaxis, :]
x_col = x[:, np.newaxis]
print(f'column vector with: {x_row.shape}')
print(f'row vector with: {x_col.shape}')


(3,)
(1, 3)
column vector with: (1, 3)
row vector with: (3, 1)


### Array Concatenation and Splitting

In [63]:
x = np.array([1,2,3])
y = np.array([3,2,1])
print(np.concatenate([x, y]))

[1 2 3 3 2 1]


In [64]:
z = [99, 99, 99]
print(np.concatenate([z,x,y,z,]))

[99 99 99  1  2  3  3  2  1 99 99 99]
